language: generic

sudo: false
cache:
  directories:
  - "$HOME/.racket"
env:
  global:
  - RACKET_DIR=~/racket
  - RACKET_VERSION=6.12
  - secure: aN+Sotj+a0OOUkTMFuk7q9r5gW7PSzEnc22wOZNymnJtY8lXOGQWzvPQE32jB0sWgmMjrVxt6HrwpQpF3Tr/FyxliafcDDkcMwto0/H4OiN8EidCufVYY/p1O6cTCJ75N4UtRsmM9BfdTdP0ZCFdmE4PmWr6sOlSGUZ/a6xMAkWCNOXv0/aCHfeKtdB4i+y7hWA1/4RMBygRQAiN7hHkFwv2ojccwkCgd/nFEds9h+tGQq5g1y1BCo7OGgNfs60xp8qoDewAkqfXJWmyMWGq1MhVQxVRK/PhpLNpTxw3NbiB5iJFk/Dc8nrg/ZOl8GEQULndWRr73dLcuL4zOx4qO1ChWEhrWkX02+Eb38M4zkBLQ/bTaAhgxzyxrxH5waCQWAA78jembX0YXOvdvIm1CwFIrpttfZGRShNZT1lJ4NmvfOUcvREQ4NsJ3xhYjf6zfIbYtQpnOaxTzFQTjQTHbrRTkIAooVdvrgsaZ+87aVlO5hWVcmdUGp/nMQh6kWiV+uV11T/sJMiVF46rREwab+X5yrvt1KIScWGAbSxXxHY/lCr3K7DgZVWg1y1GY7jwxMysh4wiLR5ghue7iP5Em6LzQY1tfoHD9FZbIzV6yk0ZX6+h9ilpkondTt2t0egU1vyo4rgTkngJPPN5bJvJoPq3e+mRRriYipCqs9wYHjY=

addons:
  apt:
    packages:
    - python-pygments
    - fonts-linuxlibertine

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- "./install-racket.sh"
- export PATH="${RACKET_DIR}/bin:${PATH}"
install:
- racket website.rkt -b && cd $TRAVIS_BUILD_DIR
script:
- echo 0
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
